apiVersion: v1
kind: Secret
data: # password is Pa$$w0rd
  password: JDJhJDEwJFI0RGQwNE1TUTlDSnptOFZYQy5IVE9janBJenplSXRwaW1NVFgxL2p1bWJZSHpXcnNpQ29h
metadata:
  name: dev1-password
  namespace: gloo-portal
type: opaque
