apiVersion: portal.gloo.solo.io/v1beta1
kind: Portal
metadata:
  name: httpbin-portal
  namespace: default
spec:
  displayName: Httpbin Portal
  description: The Gloo Portal for the Httpbin API
  banner:
    fetchUrl: https://s3.amazonaws.com/mashape-production-logos/apis/53aa61b2e4b0596140342001_medium
  favicon:
    fetchUrl: https://s3.amazonaws.com/mashape-production-logos/apis/53aa61b2e4b0596140342001_medium
  primaryLogo:
    fetchUrl: https://s3.amazonaws.com/mashape-production-logos/apis/53aa61b2e4b0596140342001_medium
  customStyling: {}
  staticPages: []

  domains:
  # If you are using Gloo Edge and the Gateway is listening on a port other than 80, 
  # you need to include a domain in this format: <DOMAIN>:<INGRESS_PORT> as we do below
  - httpbin.example.com

  # This will include all API product of the environment in the portal
  publishedEnvironments:
  - name: dev-httpbin
    namespace: default
